spring:
  datasource:
    driverClassName: org.jdbcdslog.DriverLoggingProxy
    url: jdbc:jdbcdslog:sqlserver://10.128.30.22;targetDriver=com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: bp_dev
    password: bp_dev
  
server:
  contextPath: /profile
  port: 40002
